name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest pytest-testmon mypy
          pip install -e .
          pip install types-requests types-beautifulsoup4 types-regex types-chevron

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files

      - name: Run unittests
        run: |
          pytest tests --ignore=tests/integration/test_resolution.py --durations=10 / --testmon
